var namespaceagg__util =
[
    [ "AggMemberDataset", "d4/d35/classagg__util_1_1AggMemberDataset.html", "d4/d35/classagg__util_1_1AggMemberDataset" ],
    [ "AggMemberDatasetDDSWrapper", "dd/dc1/classagg__util_1_1AggMemberDatasetDDSWrapper.html", "dd/dc1/classagg__util_1_1AggMemberDatasetDDSWrapper" ],
    [ "AggMemberDatasetDimensionCache", "d7/d33/classagg__util_1_1AggMemberDatasetDimensionCache.html", "d7/d33/classagg__util_1_1AggMemberDatasetDimensionCache" ],
    [ "AggMemberDatasetSharedDDSWrapper", "d4/d66/classagg__util_1_1AggMemberDatasetSharedDDSWrapper.html", "d4/d66/classagg__util_1_1AggMemberDatasetSharedDDSWrapper" ],
    [ "AggMemberDatasetUsingLocationRef", "da/d77/classagg__util_1_1AggMemberDatasetUsingLocationRef.html", "da/d77/classagg__util_1_1AggMemberDatasetUsingLocationRef" ],
    [ "AggMemberDatasetWithDimensionCacheBase", "d5/d72/classagg__util_1_1AggMemberDatasetWithDimensionCacheBase.html", "d5/d72/classagg__util_1_1AggMemberDatasetWithDimensionCacheBase" ],
    [ "AggregationException", "d3/dc5/classagg__util_1_1AggregationException.html", "d3/dc5/classagg__util_1_1AggregationException" ],
    [ "AggregationUtil", "d2/dd8/classagg__util_1_1AggregationUtil.html", "d2/dd8/classagg__util_1_1AggregationUtil" ],
    [ "ArrayAggregateOnOuterDimension", "d8/d43/classagg__util_1_1ArrayAggregateOnOuterDimension.html", "d8/d43/classagg__util_1_1ArrayAggregateOnOuterDimension" ],
    [ "ArrayAggregationBase", "de/df4/classagg__util_1_1ArrayAggregationBase.html", "de/df4/classagg__util_1_1ArrayAggregationBase" ],
    [ "ArrayGetterInterface", "da/d7d/structagg__util_1_1ArrayGetterInterface.html", "da/d7d/structagg__util_1_1ArrayGetterInterface" ],
    [ "ArrayJoinExistingAggregation", "d1/d2c/classagg__util_1_1ArrayJoinExistingAggregation.html", "d1/d2c/classagg__util_1_1ArrayJoinExistingAggregation" ],
    [ "BadWeakPtr", "d1/d3c/classagg__util_1_1BadWeakPtr.html", "d1/d3c/classagg__util_1_1BadWeakPtr" ],
    [ "DDSAccessInterface", "d4/d7c/classagg__util_1_1DDSAccessInterface.html", "d4/d7c/classagg__util_1_1DDSAccessInterface" ],
    [ "DDSAccessRCInterface", "d4/d01/classagg__util_1_1DDSAccessRCInterface.html", "d4/d01/classagg__util_1_1DDSAccessRCInterface" ],
    [ "DDSLoader", "d4/dfc/classagg__util_1_1DDSLoader.html", "d4/dfc/classagg__util_1_1DDSLoader" ],
    [ "Dimension", "da/dcb/structagg__util_1_1Dimension.html", "da/dcb/structagg__util_1_1Dimension" ],
    [ "DimensionNotFoundException", "dc/d2c/classagg__util_1_1DimensionNotFoundException.html", "dc/d2c/classagg__util_1_1DimensionNotFoundException" ],
    [ "DirectoryUtil", "d3/d43/classagg__util_1_1DirectoryUtil.html", "d3/d43/classagg__util_1_1DirectoryUtil" ],
    [ "FileInfo", "dd/df5/classagg__util_1_1FileInfo.html", "dd/df5/classagg__util_1_1FileInfo" ],
    [ "GridAggregateOnOuterDimension", "da/d90/classagg__util_1_1GridAggregateOnOuterDimension.html", "da/d90/classagg__util_1_1GridAggregateOnOuterDimension" ],
    [ "GridAggregationBase", "d3/dfb/classagg__util_1_1GridAggregationBase.html", "d3/dfb/classagg__util_1_1GridAggregationBase" ],
    [ "GridJoinExistingAggregation", "d7/d7e/classagg__util_1_1GridJoinExistingAggregation.html", "d7/d7e/classagg__util_1_1GridJoinExistingAggregation" ],
    [ "RCObject", "d2/dfb/classagg__util_1_1RCObject.html", "d2/dfb/classagg__util_1_1RCObject" ],
    [ "RCObjectInterface", "d5/d42/classagg__util_1_1RCObjectInterface.html", "d5/d42/classagg__util_1_1RCObjectInterface" ],
    [ "RCObjectPool", "d6/d89/classagg__util_1_1RCObjectPool.html", "d6/d89/classagg__util_1_1RCObjectPool" ],
    [ "RCPtr", "d6/d10/classagg__util_1_1RCPtr.html", "d6/d10/classagg__util_1_1RCPtr" ],
    [ "SimpleTimeParser", "d5/d32/classagg__util_1_1SimpleTimeParser.html", "d5/d32/classagg__util_1_1SimpleTimeParser" ],
    [ "TopLevelArrayGetter", "d0/d2e/structagg__util_1_1TopLevelArrayGetter.html", "d0/d2e/structagg__util_1_1TopLevelArrayGetter" ],
    [ "TopLevelGridDataArrayGetter", "de/d1e/structagg__util_1_1TopLevelGridDataArrayGetter.html", "de/d1e/structagg__util_1_1TopLevelGridDataArrayGetter" ],
    [ "TopLevelGridMapArrayGetter", "dc/db8/structagg__util_1_1TopLevelGridMapArrayGetter.html", "dc/db8/structagg__util_1_1TopLevelGridMapArrayGetter" ],
    [ "UseCountHitZeroCB", "db/db0/classagg__util_1_1UseCountHitZeroCB.html", "db/db0/classagg__util_1_1UseCountHitZeroCB" ],
    [ "WeakRCPtr", "d6/d17/classagg__util_1_1WeakRCPtr.html", "d6/d17/classagg__util_1_1WeakRCPtr" ]
];